# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y241isGphSLGe6G1xKSXw_davvxqABHM
"""

"""
src/models.py

Módulo reusable para Experiment Tracker.

Contiene funciones para:
1. Entrenar modelos baseline.
2. Guardar modelos con joblib.
3. Cargar modelos persistidos.
4. Evaluar modelos en test.
5. Registrar experimentos en experiments_log.csv.
6. Validar que un modelo puede cargarse y predecir.
7. Crear logs desde tablas de resultados existentes.

Este archivo se usa en Sprint 3 y también sirve como base para Sprint 4.
"""

import os
import json
import joblib
import pandas as pd

from datetime import datetime

from sklearn.model_selection import cross_validate
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)


# ============================================================
# 1. Utilidades generales
# ============================================================

def ensure_dir(path):
    """
    Crea un directorio si no existe.
    """
    if path:
        os.makedirs(path, exist_ok=True)


def save_model(model, model_path):
    """
    Guarda un modelo o pipeline con joblib.
    """
    ensure_dir(os.path.dirname(model_path))
    joblib.dump(model, model_path)
    return model_path


def load_model(model_path):
    """
    Carga un modelo o pipeline guardado con joblib.
    """
    return joblib.load(model_path)


# ============================================================
# 2. Entrenamiento y persistencia de modelos baseline
# ============================================================

def train_baseline(pipe, X, y, name, models_dir="../models"):
    """
    Entrena y guarda un modelo baseline.

    Parameters
    ----------
    pipe : sklearn Pipeline o estimator
        Modelo o pipeline completo.
    X : pandas.DataFrame
        Variables predictoras.
    y : pandas.Series
        Variable objetivo.
    name : str
        Nombre corto del modelo. Ejemplo: "lr", "rf", "xgb".
    models_dir : str
        Carpeta donde se guardará el modelo.

    Returns
    -------
    pipe : estimator
        Modelo entrenado.
    model_path : str
        Ruta del modelo guardado.
    """
    ensure_dir(models_dir)

    pipe.fit(X, y)

    model_path = os.path.join(models_dir, f"baseline_{name}.pkl")
    joblib.dump(pipe, model_path)

    return pipe, model_path


# ============================================================
# 3. Evaluación con cross-validation
# ============================================================

def evaluate_model(pipe, X, y, cv, scoring):
    """
    Evalúa un modelo con cross-validation.

    Parameters
    ----------
    pipe : sklearn Pipeline o estimator
        Modelo o pipeline a evaluar.
    X : pandas.DataFrame
        Variables predictoras.
    y : pandas.Series
        Variable objetivo.
    cv : cross-validation splitter
        Ejemplo: StratifiedKFold.
    scoring : dict or list
        Métricas de evaluación.

    Returns
    -------
    results : dict
        Resultado completo de cross_validate.
    metrics_summary : dict
        Promedio y desviación estándar de cada métrica.
    """

    results = cross_validate(
        pipe,
        X,
        y,
        cv=cv,
        scoring=scoring,
        return_train_score=True
    )

    metrics_summary = {}

    if isinstance(scoring, dict):
        metric_names = scoring.keys()
    else:
        metric_names = scoring

    for metric_name in metric_names:
        test_key = f"test_{metric_name}"
        train_key = f"train_{metric_name}"

        metrics_summary[f"{metric_name}_cv_mean"] = results[test_key].mean()
        metrics_summary[f"{metric_name}_cv_std"] = results[test_key].std()

        if train_key in results:
            metrics_summary[f"{metric_name}_train_mean"] = results[train_key].mean()
            metrics_summary[f"{metric_name}_train_std"] = results[train_key].std()

    return results, metrics_summary


# ============================================================
# 4. Evaluación sobre test set
# ============================================================

def evaluate_on_test(model, X_test, y_test, positive_label=1):
    """
    Evalúa un modelo ya entrenado sobre el conjunto de test.

    Parameters
    ----------
    model : sklearn Pipeline o estimator
        Modelo entrenado.
    X_test : pandas.DataFrame
        Variables predictoras de test.
    y_test : pandas.Series
        Target real.
    positive_label : int or str
        Clase positiva.

    Returns
    -------
    metrics : dict
        Métricas principales.
    report : dict
        Classification report.
    cm : array
        Matriz de confusión.
    """

    y_pred = model.predict(X_test)

    metrics = {
        "accuracy": accuracy_score(y_test, y_pred),
        "precision": precision_score(
            y_test,
            y_pred,
            pos_label=positive_label,
            zero_division=0
        ),
        "recall": recall_score(
            y_test,
            y_pred,
            pos_label=positive_label,
            zero_division=0
        ),
        "f1": f1_score(
            y_test,
            y_pred,
            pos_label=positive_label,
            zero_division=0
        )
    }

    if hasattr(model, "predict_proba"):
        y_proba = model.predict_proba(X_test)[:, 1]
        metrics["roc_auc"] = roc_auc_score(y_test, y_proba)
    else:
        y_proba = None
        metrics["roc_auc"] = None

    report = classification_report(
        y_test,
        y_pred,
        output_dict=True,
        zero_division=0
    )

    cm = confusion_matrix(y_test, y_pred)

    return metrics, report, cm


# ============================================================
# 5. Registro de experimentos
# ============================================================

def log_experiment(
    name,
    params,
    metrics,
    path="../models/experiments_log.csv",
    model_path=None,
    selected=False,
    notes="",
    sprint="Sprint 3",
    stage="Baseline Modeling",
    experiment_type="baseline"
):
    """
    Registra un experimento en experiments_log.csv.

    Parameters
    ----------
    name : str
        Nombre del modelo.
    params : dict
        Parámetros del modelo o experimento.
    metrics : dict
        Métricas obtenidas.
    path : str
        Ruta del log.
    model_path : str
        Ruta del modelo persistido.
    selected : bool
        Indica si fue seleccionado como candidato.
    notes : str
        Comentarios.
    sprint : str
        Sprint asociado.
    stage : str
        Etapa o PB asociado.
    experiment_type : str
        Tipo de experimento.
    """

    ensure_dir(os.path.dirname(path))

    row = {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "sprint": sprint,
        "stage": stage,
        "model": name,
        "experiment_type": experiment_type,
        "params": json.dumps(params, ensure_ascii=False),
        "model_path": model_path,
        "selected": selected,
        "notes": notes,
        **metrics
    }

    df_row = pd.DataFrame([row])

    if os.path.exists(path):
        df_row.to_csv(path, mode="a", header=False, index=False)
    else:
        df_row.to_csv(path, index=False)

    return row


# ============================================================
# 6. Flujo completo: entrenar, evaluar y registrar
# ============================================================

def train_evaluate_log(
    pipe,
    X,
    y,
    name,
    params,
    cv,
    scoring,
    models_dir="../models",
    log_path="../models/experiments_log.csv",
    selected=False,
    notes="",
    sprint="Sprint 3",
    stage="Baseline Modeling",
    experiment_type="baseline"
):
    """
    Ejecuta el flujo completo:

    1. Entrena modelo.
    2. Guarda modelo con joblib.
    3. Evalúa con cross-validation.
    4. Registra en experiments_log.csv.
    """

    fitted_pipe, model_path = train_baseline(
        pipe=pipe,
        X=X,
        y=y,
        name=name,
        models_dir=models_dir
    )

    _, metrics_summary = evaluate_model(
        pipe=fitted_pipe,
        X=X,
        y=y,
        cv=cv,
        scoring=scoring
    )

    log_experiment(
        name=name,
        params=params,
        metrics=metrics_summary,
        path=log_path,
        model_path=model_path,
        selected=selected,
        notes=notes,
        sprint=sprint,
        stage=stage,
        experiment_type=experiment_type
    )

    return fitted_pipe, metrics_summary, model_path


# ============================================================
# 7. Validación de carga y predicción
# ============================================================

def validate_model_load_and_predict(model_path, X_sample):
    """
    Valida que un modelo guardado se puede cargar y predecir.
    """

    model = load_model(model_path)
    preds = model.predict(X_sample)

    return preds


def validate_saved_models(model_paths, X_sample):
    """
    Valida varios modelos guardados.

    Parameters
    ----------
    model_paths : dict
        Ejemplo:
        {
            "rf": "../models/baseline_rf.pkl",
            "final_model": "../models/final_model.pkl"
        }

    X_sample : pandas.DataFrame
        Muestra de prueba.

    Returns
    -------
    validation_results : dict
        Predicciones por modelo.
    """

    validation_results = {}

    for name, path in model_paths.items():
        model = load_model(path)
        preds = model.predict(X_sample)
        validation_results[name] = preds

    return validation_results


# ============================================================
# 8. Crear log desde tabla comparativa existente
# ============================================================

def create_experiments_log_from_results(
    df_results,
    path="../models/experiments_log.csv",
    selected_model="rf",
    sprint="Sprint 3",
    stage="Model Comparison",
    experiment_type="comparison"
):
    """
    Crea experiments_log.csv desde una tabla comparativa existente.

    Admite columnas:
    - modelo / model / Modelo
    - accuracy / Accuracy
    - precision / Precision
    - recall / Recall
    - f1 / F1-Score
    - roc_auc / AUC-ROC
    """

    ensure_dir(os.path.dirname(path))

    rows = []

    for _, row in df_results.iterrows():

        model_name = (
            row.get("modelo")
            if "modelo" in row.index
            else row.get("model", row.get("Modelo"))
        )

        model_key = str(model_name).lower().replace(" ", "_")

        record = {
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "sprint": sprint,
            "stage": stage,
            "model": model_name,
            "experiment_type": experiment_type,
            "params": "baseline_default",
            "model_path": f"../models/baseline_{model_key}.pkl",
            "accuracy": row.get("accuracy", row.get("Accuracy")),
            "precision": row.get("precision", row.get("Precision")),
            "recall": row.get("recall", row.get("Recall")),
            "f1": row.get("f1", row.get("F1-Score")),
            "roc_auc": row.get("roc_auc", row.get("AUC-ROC")),
            "selected": str(model_name).lower() == str(selected_model).lower(),
            "notes": (
                "Modelo seleccionado como candidato."
                if str(model_name).lower() == str(selected_model).lower()
                else "Modelo evaluado."
            )
        }

        rows.append(record)

    df_log = pd.DataFrame(rows)
    df_log.to_csv(path, index=False)

    return df_log


# ============================================================
# 9. Registrar resultado final del Sprint 4
# ============================================================

def log_final_model_result(
    model_name,
    metrics,
    params=None,
    model_path="../models/final_model.pkl",
    path="../models/experiments_log.csv",
    notes="Modelo final seleccionado y validado en test set."
):
    """
    Registra el modelo final del Sprint 4 en experiments_log.csv.
    """

    params = params or {}

    row = {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "sprint": "Sprint 4",
        "stage": "PB-15 Final Validation",
        "model": model_name,
        "experiment_type": "final_validation",
        "params": json.dumps(params, ensure_ascii=False),
        "model_path": model_path,
        "selected": True,
        "notes": notes,
        **metrics
    }

    ensure_dir(os.path.dirname(path))

    df_row = pd.DataFrame([row])

    if os.path.exists(path):
        df_row.to_csv(path, mode="a", header=False, index=False)
    else:
        df_row.to_csv(path, index=False)

    return row