# -*- coding: utf-8 -*-
"""tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zKQbEnrX8jX0zYHhED1SjiHwE-Pr5X6B
"""

"""
src/tuning.py

Rol 5: Experiment Tracker — Sprint 4

Este módulo contiene utilidades reutilizables para:
1. Ejecutar tuning con GridSearchCV o RandomizedSearchCV.
2. Persistir modelos tuneados con joblib.
3. Registrar experimentos de tuning con métricas, parámetros y tiempo.
4. Actualizar experiments_log.csv.
5. Validar carga y predicción de modelos tuneados/finales.

Uso esperado:
- 12_hyperparam_tuning.ipynb
- 13_ensembles.ipynb
- 14_final_validation.ipynb
- 15_experiment_tracker_sprint4.ipynb
"""

import os
import json
import time
import joblib
import pandas as pd

from datetime import datetime
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)


# ============================================================
# 1. UTILIDADES GENERALES
# ============================================================

def ensure_dir(path):
    """
    Crea un directorio si no existe.
    """
    if path:
        os.makedirs(path, exist_ok=True)


def save_model(model, model_path):
    """
    Persiste un modelo con joblib.
    """
    ensure_dir(os.path.dirname(model_path))
    joblib.dump(model, model_path)
    return model_path


def load_model(model_path):
    """
    Carga un modelo persistido con joblib.
    """
    return joblib.load(model_path)


# ============================================================
# 2. TUNING CON GRIDSEARCHCV
# ============================================================

def tune_model_grid(
    pipe,
    param_grid,
    X,
    y,
    cv,
    scoring="f1",
    name="model",
    models_dir="../models",
    log_path="../models/experiments_log.csv",
    n_jobs=-1,
    verbose=1,
    notes="Tuning con GridSearchCV"
):
    """
    Ejecuta GridSearchCV, guarda el mejor modelo y registra el experimento.

    Parameters
    ----------
    pipe : sklearn Pipeline o estimator
        Modelo o pipeline a tunear.

    param_grid : dict
        Espacio de búsqueda para GridSearchCV.

    X, y :
        Datos de entrenamiento.

    cv :
        Estrategia de validación cruzada.

    scoring : str
        Métrica principal. Ejemplo: "f1", "recall", "roc_auc".

    name : str
        Nombre corto del modelo. Ejemplo: "rf", "lr", "xgb".

    Returns
    -------
    grid : GridSearchCV
        Objeto entrenado.

    result : dict
        Registro del experimento.
    """

    ensure_dir(models_dir)

    start = time.time()

    grid = GridSearchCV(
        estimator=pipe,
        param_grid=param_grid,
        scoring=scoring,
        cv=cv,
        n_jobs=n_jobs,
        verbose=verbose,
        return_train_score=True
    )

    grid.fit(X, y)

    elapsed = round(time.time() - start, 2)

    model_path = os.path.join(models_dir, f"tuned_{name}.pkl")
    save_model(grid.best_estimator_, model_path)

    result = {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "sprint": "Sprint 4",
        "stage": "PB-13 Hyperparameter Tuning",
        "model": name,
        "experiment_type": "GridSearchCV",
        "scoring": scoring,
        "best_score": grid.best_score_,
        "best_params": json.dumps(grid.best_params_, ensure_ascii=False),
        "time_seconds": elapsed,
        "model_path": model_path,
        "selected": False,
        "notes": notes
    }

    append_experiment(result, log_path)

    return grid, result


# ============================================================
# 3. TUNING CON RANDOMIZEDSEARCHCV
# ============================================================

def tune_model_randomized(
    pipe,
    param_dist,
    X,
    y,
    cv,
    scoring="f1",
    name="model",
    n_iter=20,
    models_dir="../models",
    log_path="../models/experiments_log.csv",
    random_state=42,
    n_jobs=-1,
    verbose=1,
    notes="Tuning con RandomizedSearchCV"
):
    """
    Ejecuta RandomizedSearchCV, guarda el mejor modelo y registra el experimento.
    """

    ensure_dir(models_dir)

    start = time.time()

    search = RandomizedSearchCV(
        estimator=pipe,
        param_distributions=param_dist,
        n_iter=n_iter,
        scoring=scoring,
        cv=cv,
        random_state=random_state,
        n_jobs=n_jobs,
        verbose=verbose,
        return_train_score=True
    )

    search.fit(X, y)

    elapsed = round(time.time() - start, 2)

    model_path = os.path.join(models_dir, f"tuned_{name}.pkl")
    save_model(search.best_estimator_, model_path)

    result = {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "sprint": "Sprint 4",
        "stage": "PB-13 Hyperparameter Tuning",
        "model": name,
        "experiment_type": "RandomizedSearchCV",
        "scoring": scoring,
        "best_score": search.best_score_,
        "best_params": json.dumps(search.best_params_, ensure_ascii=False),
        "time_seconds": elapsed,
        "model_path": model_path,
        "selected": False,
        "notes": notes
    }

    append_experiment(result, log_path)

    return search, result


# ============================================================
# 4. EVALUACIÓN EN TEST
# ============================================================

def evaluate_model_on_test(model, X_test, y_test, positive_label=1):
    """
    Evalúa un modelo en el conjunto de test.

    Returns
    -------
    metrics : dict
        Métricas principales.

    report : dict
        Classification report.

    cm : array
        Matriz de confusión.
    """

    y_pred = model.predict(X_test)

    metrics = {
        "accuracy": accuracy_score(y_test, y_pred),
        "precision": precision_score(
            y_test,
            y_pred,
            pos_label=positive_label,
            zero_division=0
        ),
        "recall": recall_score(
            y_test,
            y_pred,
            pos_label=positive_label,
            zero_division=0
        ),
        "f1": f1_score(
            y_test,
            y_pred,
            pos_label=positive_label,
            zero_division=0
        )
    }

    if hasattr(model, "predict_proba"):
        y_proba = model.predict_proba(X_test)[:, 1]
        metrics["roc_auc"] = roc_auc_score(y_test, y_proba)
    else:
        y_proba = None
        metrics["roc_auc"] = None

    report = classification_report(
        y_test,
        y_pred,
        output_dict=True,
        zero_division=0
    )

    cm = confusion_matrix(y_test, y_pred)

    return metrics, report, cm


# ============================================================
# 5. REGISTRO DE EXPERIMENTOS
# ============================================================

def append_experiment(result, log_path="../models/experiments_log.csv"):
    """
    Agrega un experimento al archivo experiments_log.csv.
    """

    ensure_dir(os.path.dirname(log_path))

    df_row = pd.DataFrame([result])

    if os.path.exists(log_path):
        df_row.to_csv(log_path, mode="a", header=False, index=False)
    else:
        df_row.to_csv(log_path, index=False)

    return result


def log_sprint4_result(
    model,
    experiment_type,
    metrics,
    params=None,
    model_path=None,
    stage="Sprint 4",
    selected=False,
    notes="",
    log_path="../models/experiments_log.csv",
    time_seconds=None
):
    """
    Registra manualmente un resultado del Sprint 4.

    Útil para registrar resultados de:
    - ensambles
    - stacking
    - modelo final
    - validación final
    """

    params = params or {}

    result = {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "sprint": "Sprint 4",
        "stage": stage,
        "model": model,
        "experiment_type": experiment_type,
        "params": json.dumps(params, ensure_ascii=False),
        "accuracy": metrics.get("accuracy"),
        "precision": metrics.get("precision"),
        "recall": metrics.get("recall"),
        "f1": metrics.get("f1"),
        "roc_auc": metrics.get("roc_auc"),
        "time_seconds": time_seconds,
        "model_path": model_path,
        "selected": selected,
        "notes": notes
    }

    append_experiment(result, log_path)

    return result


# ============================================================
# 6. VALIDACIÓN DE CARGA Y PREDICCIÓN
# ============================================================

def validate_model_load_and_predict(model_path, X_sample):
    """
    Valida que un modelo guardado pueda cargarse y generar predicciones.
    """

    model = load_model(model_path)

    preds = model.predict(X_sample)

    return preds


def validate_many_models(model_paths, X_sample):
    """
    Valida varios modelos persistidos.

    Parameters
    ----------
    model_paths : dict
        Ejemplo:
        {
            "tuned_rf": "../models/tuned_rf.pkl",
            "final_model": "../models/final_model.pkl"
        }
    """

    results = {}

    for name, path in model_paths.items():
        model = load_model(path)
        preds = model.predict(X_sample)
        results[name] = preds

    return results


# ============================================================
# 7. BOOTSTRAP PARA INTERVALOS DE CONFIANZA
# ============================================================

def bootstrap_metric(y_true, y_score, metric_fn, n_iterations=1000, random_state=42):
    """
    Calcula intervalo de confianza al 95% usando bootstrap.

    Parameters
    ----------
    y_true : array-like
        Etiquetas reales.

    y_score : array-like
        Predicciones o probabilidades.

    metric_fn : callable
        Función de métrica. Ejemplo: roc_auc_score, f1_score.

    Returns
    -------
    ci : array
        Percentiles [2.5, 97.5].
    """

    import numpy as np

    rng = np.random.RandomState(random_state)

    y_true_arr = np.array(y_true)
    y_score_arr = np.array(y_score)

    scores = []

    for _ in range(n_iterations):
        idx = rng.randint(0, len(y_true_arr), len(y_true_arr))

        if len(np.unique(y_true_arr[idx])) < 2:
            continue

        score = metric_fn(y_true_arr[idx], y_score_arr[idx])
        scores.append(score)

    return np.percentile(scores, [2.5, 97.5])